### PR TITLE
Update dependencies - specifically, tokio, prost, and tonic

### PR DESCRIPTION
**Pull request by colin-grapl**
I've updated three dependencies as part of this PR - tokio, prost, and tonic.

tokio has recently reached 1.0, and since it's a pretty core library, and differing versions can be problematic across crates, I think updating it to 1.0 ASAP makes the most sense - especially since they have some strong semver guarantees post 1.0.

tonic being updated pulls in the 1.0 of tokio, and also the updated prost 0.7.

I've run all of the integration tests locally and everything passes.

### CODE REVIEW

**Comment by selmeci** [comment]
Hi @colin-grapl, thank you for PR. We should probably bump up new version 0.9 because if someone is using libraries which have dependencies for old tokio version, it could break it code.

**Comment by colin-grapl** [comment]
Sure thing, I've updated the PR.

**Comment by selmeci** [comment]
I've just check travis for jobs results and there are some improvements for sync client required:

https://travis-ci.org/github/selmeci/dgraph-tonic/jobs/755072451

We should remove unnecessary mutex and simplify all code for synchronous features.

Can you handle it, please?

Thanks.

**Comment by colin-grapl** [comment]
Done

**Pull request merged**
