### PR TITLE
adding commit flag in upsert

### LINKED ISSUE #7: Need to be able to control upsert commit now
We have an upsert operation used in the middle of a transaction, but right now `dgraph-tonic` doesn't allow upsert to control whether or not the txn should be committed or not.

Proposing to add two more upsert operations with `&mut self` and not setting the `commit_now` flag in the request.

Some reference I have in other client implementations:

https://github.com/dgraph-io/dgo#running-an-upsert-query--mutation
https://github.com/dgraph-io/dgraph-js#running-an-upsert-query--mutation

Although the dGraph documentation recommends committing after upsert, we have a long update chain txn that currently will produce wrong side effects if we don't run this upsert in the middle of the txn.

### PR DESCRIPTION
**Pull request by lhr0909**
resolves #7

### CODE REVIEW

**Comment by lhr0909** [comment]
Not sure why test doesn't pass on local, maybe it is me not knowing how to run the test with features. I am hoping this test passes.

**Comment by selmeci** [comment]
I see where is problem. Rust also check code in documentation. I'm going to merge this pull request into new branch, fix it and than I will merge it to master branch.

I add commit_now variant for upsert operation, also.

**Comment by selmeci** [comment]
You have already done it :+1: . I will fix only docs.

**Comment by selmeci** [comment]
I fixed docs, but some test is not passing.

- sync::txn::mutated::Mutate::upsert (line 250) ... FAILED
- sync::txn::mutated::Mutate::upsert_with_vars (line 431) ... FAILED

It fails with message:
```
Schema is not updated: CannotAlter(Status { code: Unknown, message: "Pending transactions found. Please retry operation" })', src/sync/txn/mutated.rs:35:5
```

It seems that there are some uncommitted transactions in Dgraph.
I need to figure out why.

Dgraph logs:
```
server_1  | I0515 16:20:30.602208      16 server.go:1122] Got Alter request from "172.23.0.1:46006"
server_1  | I0515 16:20:30.602733      16 server.go:275] Got schema: &{Preds:[predicate:"email" value_type:STRING directive:INDEX tokenizer:"exact" ] Types:[]}
server_1  | E0515 16:20:30.612919      16 draft.go:593] Applying proposal. Error: Pending transactions found. Please retry operation. Proposal: "mutations:<group_id:1 start_ts:130 schema:<predicate:\"email\" value_type:STRING directive:INDEX tokenizer:\"exact\" > > key:\"01-16995568804923020646\" index:185 ".
server_1  | I0515 16:20:30.613071      16 server.go:290] ALTER op: schema:"email: string @index(exact) ."  done
server_1  | I0515 16:20:30.621288      16 draft.go:1230] TryAbort 1 txns with start ts. Error: <nil>
server_1  | I0515 16:20:30.621305      16 draft.go:1253] TryAbort selectively proposing only aborted txns: txns:<start_ts:128 > 
server_1  | I0515 16:20:30.637479      16 mutation.go:830] tryAbortTransactions for 1 txns. Error: <nil>
```

**Comment by lhr0909** [comment]
@selmeci Ahh I see, I think in the test we may still need to explicitly commit the transactions after `upsert` and `upsert_with_vars`

**Comment by selmeci** [comment]
@lhr0909 problem is solved. There was two kind of problems:

1. transactions in upsert examples should be mutable
2. [transactions in upsert functions without commit now must not be](https://github.com/selmeci/dgraph-tonic/commit/a5b30037c58fa5e3faeb4390df92dfdb8c624a85)

New version is published.

**Pull request merged**
